[project.metadata]
name = "chirp3d example"
version = "1.0.0"
identifier = "com.kraxarn.chirp3d_example"
creator = "kraxarn"
copyright = "Copyright (c) 2026 kraxarn"
url = "https://github.com/kraxarn/chirp3d"
type = "game"

[project.window]
title = "chirp3d example"
size = [1280, 720]
fullscreen = false
icon = ""

[project.run]
map = "test"

[assets]
textures = ["dark", "green", "light", "orange", "purple", "red"]
models = ["blaster"]

[input]
move_forward  = { keycode = "w", axis = "left_y",  axis_range = [0.05, 1.0  ] }
move_backward = { keycode = "s", axis = "left_y",  axis_range = [-1.0, -0.05] }
move_left     = { keycode = "a", axis = "left_x",  axis_range = [-1.0, -0.05] }
move_right    = { keycode = "d", axis = "left_x",  axis_range = [0.05, 1.0  ] }
move_up       = { keycode = "q", axis = "right_y", axis_range = [0.05, 1.0  ] }
move_down     = { keycode = "e", axis = "right_y", axis_range = [-1.0, -0.05] }
jump          = { keycode = "space" }