name: Linux (gcc)

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:questing

    steps:
      - name: Install Checkout Dependencies
        run: apt update && apt install -y git

      - uses: actions/checkout@v5

      - name: Install Dependencies
        run: apt install -y libsdl3-dev

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        run: cmake --build build --config $BUILD_TYPE
