name: Linux (arm64, gcc)

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Install Action Dependencies
        run: apt update && apt install -y git

      - uses: actions/checkout@v5

      # setup-clang script requires pwsh
      # https://learn.microsoft.com/en-us/powershell/scripting/install/install-other-linux#installation-using-a-binary-archive-file
      - name: Install PowerShell
        run: |
          apt install -y curl ca-certificates libc6 libgcc-s1 libgssapi-krb5-2 libicu74 libssl3t64 libstdc++6 tzdata zlib1g
          curl -L -o /tmp/powershell.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v7.5.4/powershell-7.5.4-linux-arm64.tar.gz
          mkdir -p /opt/microsoft/powershell/7
          tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7
          chmod +x /opt/microsoft/powershell/7/pwsh
          ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh

      - name: Set up compiler
        uses: egor-tensin/setup-clang@v2
        with:
          version: '19'
          cc: '1'

      # https://wiki.libsdl.org/SDL3/README-linux
      - name: Install SDL3 Dependencies
        run: apt install -y build-essential make pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        run: cmake --build build --config $BUILD_TYPE

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chirp3d-linux-x64
          path: |
            ${{runner.workspace}}/chirp3d/build/chirp3d
            ${{runner.workspace}}/chirp3d/build/libSDL3.so.0.4.0
