name: Linux (clang)

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    # Supported until April 2027
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5

      - name: Set up compiler
        uses: egor-tensin/setup-clang@v2
        with:
          version: '19'
          platform: 'x64'
          cc: '1'

      # https://wiki.libsdl.org/SDL3/README-linux
      - name: Install Dependencies
        run: sudo apt install -y build-essential make pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        run: cmake --build build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chirp3d-linux-x64
          path: |
            ${{runner.workspace}}/chirp3d/build/chirp3d
            ${{runner.workspace}}/chirp3d/build/libSDL3.so
