name: Linux

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: '${{ matrix.arch }}-${{ matrix.compiler }}'
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
          # Supported until April 2027
          - os: ubuntu-22.04
            compiler: clang
            arch: amd64
            build-sdl: true
            compile-flags: '-march=x86-64-v3'

          # Supported until April 2027
          - os: ubuntu-22.04-arm
            compiler: clang
            arch: arm64
            build-sdl: true

          - os: ubuntu-latest
            container: ubuntu:questing
            compiler: gcc
            arch: amd64
            build-sdl: false
            compile-flags: '-march=x86-64-v3'

    steps:
      - name: Install Checkout Dependencies
        if: ${{ matrix.container != '' }}
        run: apt update && apt install -y git

      - uses: actions/checkout@v5

      - name: Set up clang
        if: ${{ matrix.compiler == 'clang' }}
        uses: egor-tensin/setup-clang@v2
        with:
          version: '21'
          cc: '1'

      - name: Install SDL3
        if: ${{ !matrix.build-sdl }}
        run: apt install -y build-essential make pkg-config cmake libsdl3-dev

      # https://wiki.libsdl.org/SDL3/README-linux
      - name: Install SDL3 Dependencies
        if: ${{ matrix.build-sdl }}
        run: sudo apt install -y build-essential make pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '>=3.10'

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_FLAGS="${{ matrix.compile-flags }}" -DCMAKE_CXX_FLAGS="${{ matrix.compile-flags }}"

      - name: Build
        run: cmake --build build

      - name: Upload Artifact
        if: ${{ matrix.compiler == 'clang' }}
        uses: actions/upload-artifact@v4
        with:
          name: chirp3d-linux-${{ matrix.arch }}
          path: |
            ${{runner.workspace}}/chirp3d/build/chirp3d
            ${{runner.workspace}}/chirp3d/build/libSDL3.so.0.4.0
