name: macOS

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: '${{ matrix.arch }}'
    runs-on: macos-latest

    strategy:
      matrix:
        include:
          - arch: x86_64
            compiler-flags: '-march=x86-64-v3'

          - arch: arm64
            compiler-flags: '-mfloat-abi=hard -mfpu=neon'

    steps:
      - uses: actions/checkout@v5

      - name: Configure CMake
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=$BUILD_TYPE -D CMAKE_OSX_DEPLOYMENT_TARGET="10.14" -D CMAKE_OSX_ARCHITECTURES="${{ matrix.arch }}" -D CMAKE_C_FLAGS="${{ matrix.compile-flags }}" -D CMAKE_CXX_FLAGS="${{ matrix.compile-flags }}"

      - name: Build
        run: cmake --build build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chirp3d-macos-${{ matrix.arch }}
          path: ${{runner.workspace}}/chirp3d/build/chirp3d.app
