name: Windows

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release
  CMAKE_GENERATOR: "Ninja"

jobs:
  build:
    name: '${{ matrix.arch }}'
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - arch: 'x86_64'
            compile-flags: '-march=x86-64-v3'

          - arch: 'aarch64'
            compile-flags: '-target aarch64-pc-windows-msvc'

    steps:
      - uses: actions/checkout@v5

      - name: Set up compiler
        uses: egor-tensin/setup-clang@v2
        with:
          version: 'latest'
          platform: 'x64'
          cc: '1'

      - name: Configure CMake
        run: cmake -S . -B build -G "${{env.CMAKE_GENERATOR}}" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_FLAGS="${{ matrix.compile-flags }}" -DCMAKE_CXX_FLAGS="${{ matrix.compile-flags }}"

      - name: Build
        run: cmake --build build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chirp3d-windows-${{ matrix.arch }}
          path: |
            ${{runner.workspace}}\chirp3d\build\chirp3d.exe
            ${{runner.workspace}}\chirp3d\build\SDL3.dll
