name: Windows

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release
  CMAKE_GENERATOR: "Ninja"

jobs:
  build:
    name: '${{ matrix.arch }}'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: 'x86_64'
            compile-flags: '-march=x86-64-v3'

          - os: windows-11-arm
            arch: 'aarch64'
            compiler-flags: '-mfloat-abi=hard -mfpu=neon'

    steps:
      - uses: actions/checkout@v5

      - name: Set up compiler
        if: ${{ matrix.arch == 'x86_64' }}
        uses: egor-tensin/setup-clang@v2
        with:
          version: 'latest'
          cc: '1'

      # setup-clang uses choco which doesn't support aarch64
      - name: Set up compiler
        if: ${{ matrix.arch == 'aarch64' }}
        shell: powershell
        run: |
          winget install llvm --accept-package-agreements --accept-source-agreements
          $bin_dir = Join-Path (Join-Path $env:ProgramFiles LLVM) bin
          echo $bin_dir >> $env:GITHUB_PATH

      - name: Configure CMake
        run: cmake -S . -B build -G "${{env.CMAKE_GENERATOR}}" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_FLAGS="${{ matrix.compile-flags }}" -DCMAKE_CXX_FLAGS="${{ matrix.compile-flags }}"

      - name: Build
        run: cmake --build build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chirp3d-windows-${{ matrix.arch }}
          path: |
            ${{runner.workspace}}\chirp3d\build\chirp3d.exe
            ${{runner.workspace}}\chirp3d\build\SDL3.dll
