name: Windows

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release
  CMAKE_GENERATOR: "Ninja"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up compiler
        uses: egor-tensin/setup-clang@v2
        with:
          version: 'latest'
          platform: 'x64'
          cc: '1'

      - name: Configure CMake
        run: cmake -S . -B build -G "${{env.CMAKE_GENERATOR}}" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_FLAGS="-march=x86-64-v3" -DCMAKE_CXX_FLAGS="-march=x86-64-v3"

      - name: Build
        run: cmake --build build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chirp3d-windows-x64
          path: |
            ${{runner.workspace}}\chirp3d\build\chirp3d.exe
            ${{runner.workspace}}\chirp3d\build\SDL3.dll
